if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

function(extract path start_marker end_marker output)
    file(READ "${PROJECT_ROOT}/${path}" source)
    string(FIND "${source}" "${start_marker}" start)
    string(FIND "${source}" "${end_marker}" end)
    if(start LESS 0 OR end LESS_EQUAL start)
        message(FATAL_ERROR "Full-resolution FOV extraction boundaries are missing: ${start_marker}")
    endif()
    math(EXPR length "${end} - ${start}")
    string(SUBSTRING "${source}" ${start} ${length} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

set(header "src/Features/Upscaling.h")
set(source "src/Features/Upscaling.cpp")
extract("${header}" "\tstatic constexpr float kFoveatedBlendFeatherMin" "\t// Explicit profile changes" constants)
extract("${header}" "\tstruct FoveatedDispatchRect" "\tstruct PeripheryTAATile\n" rect)
extract("${header}" "\tstruct FoveatedRectCacheState" "\tstruct FoveatedEncodeRegion" cache)
extract("${header}" "\tenum class FoveatedUpscalingMode" "\tstatic const char* GetFoveatedUpscalingModeName" profile_type)
extract("${source}" "\tconstexpr float kPeripheryTAAOuterScaleMin" "\tconstexpr float kDynamicResolutionUpscalingScaleThreshold" helper_constants)
extract("${source}" "\tfloat ClampPeripheryTAACenterBlendFeather(" "\tfloat ClampFiniteUnitRange(" helpers)
extract("${source}" "\tstruct FoveatedMaskProfileParams" "\tfloat FoveatedMaskDistanceUV(" profile_parameters)
extract("${source}" "Upscaling::ActiveUpscalingFoveatedProfile Upscaling::GetActiveUpscalingFoveatedProfile()" "float Upscaling::GetActiveFoveatedSharedVisibleScale()" profile)
extract("${source}" "bool Upscaling::BuildFoveatedDispatchRects(" "bool Upscaling::GetFoveatedEncodeRegions(" build)
extract("${source}" "bool Upscaling::PrepareFullResolutionNeuralInputs(" "void Upscaling::PrepareMainFullResolutionNeuralFrame()" prepare)
extract("${source}" "bool Upscaling::ApplyFinalLdrNeuralStereo(" "bool Upscaling::PrepareFullResolutionNeuralInputs(" apply)
string(REGEX REPLACE "[ \t\r\n]+" " " apply "${apply}")
string(FIND "${prepare}" "GetActiveUpscalingFoveatedProfile()" prepare_profile)
string(FIND "${prepare}" "settings.neuralRenderingFovOnly ? &sharedMaskProfile : nullptr" prepare_selection)
if(prepare_profile LESS 0 OR prepare_selection LESS 0)
    message(FATAL_ERROR "Full-resolution guide preparation must select the active shared mask")
endif()
string(FIND "${apply}" "GetNeuralRenderingMode() == NeuralRendering::RenderingMode::FullResolution && settings.neuralRenderingFovOnly;" blend_mode)
string(FIND "${apply}" "foveatedRectCache.centerFeather : ClampFoveatedBlendFeather(settings.neuralRenderingBlendFeather)" blend_feather)
string(FIND "${apply}" "sharedFullResolutionFovMask && !FoveatedCommon::IsActiveCoverage(foveatedRectCache.centerScale)" full_shared_coverage)
if(blend_mode LESS 0 OR blend_feather LESS blend_mode OR full_shared_coverage LESS blend_feather)
    message(FATAL_ERROR "Full-resolution final blend must use the feather pinned during guide preparation")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_full_resolution_fov_types.h" "${constants}\n${rect}\n${cache}\n${profile_type}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_full_resolution_fov_under_test.h"
    "${helper_constants}\n${helpers}\n${profile_parameters}\n${profile}\n${build}")
