if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/NeuralRenderingFeature.cpp" source)
function(extract start_marker end_marker output)
    string(FIND "${source}" "${start_marker}" start)
    string(FIND "${source}" "${end_marker}" end)
    if(start EQUAL -1 OR end EQUAL -1 OR end LESS_EQUAL start)
        message(FATAL_ERROR "Neural Rendering feature settings boundaries are missing")
    endif()
    math(EXPR length "${end} - ${start}")
    string(SUBSTRING "${source}" ${start} ${length} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
extract("\tconstexpr std::array<const char*," "\tJson ProfileJson(" helpers)
extract("void NeuralRenderingFeature::LoadSettings(" "void NeuralRenderingFeature::EarlyPrepass(" methods)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_feature_settings_under_test.h"
    "namespace { using namespace NeuralRendering::Color; using Json = nlohmann::json;\n${helpers}\n}\n${methods}")
