file(READ "${PROJECT_ROOT}/src/Utils/CharacterCategoryAuthoring.cpp" source)
string(FIND "${source}" "\tstruct ActorRaceKeywords" first)
string(FIND "${source}" "\tNeuralRendering::CharacterActorBound ReadBound" last)
if(first LESS 0 OR last LESS first)
    message(FATAL_ERROR "Actor material classifier extraction anchors changed")
endif()
math(EXPR length "${last} - ${first}")
string(SUBSTRING "${source}" ${first} ${length} classifier)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/character_material_under_test.h" "${classifier}")
