if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" source)
function(extract start_marker end_marker output)
    string(FIND "${source}" "${start_marker}" start)
    string(FIND "${source}" "${end_marker}" end)
    if(start LESS 0 OR end LESS_EQUAL start)
        message(FATAL_ERROR "NR control extraction boundaries are missing")
    endif()
    math(EXPR length "${end} - ${start}")
    string(SUBSTRING "${source}" ${start} ${length} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
extract("\tvoid DrawNeuralRenderingFovWarning(" "bool Upscaling::ApplyNeuralRenderingPreset(" controls)
extract("bool Upscaling::HandleNeuralRenderingSettingsTransition(" "NeuralRendering::InsertionPoint Upscaling::GetNeuralRenderingInsertionPoint()" transition)
extract("bool Upscaling::IsPeripheryTAAEnabled(" "bool Upscaling::IsPeripheryTAAPathActive(" taa_guard)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_rendering_controls_under_test.h"
    "namespace {\n${controls}\n${transition}\n${taa_guard}")
