if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/Upscaling/VRRenderScaleDevBenchBridge.cpp" source)
string(FIND "${source}" "\ttemplate <std::size_t N>\n\tbool TryValidateActionFields(" start)
string(FIND "${source}" "\tstruct FoveationConfigurationRequest" end)
if(start EQUAL -1 OR end EQUAL -1 OR end LESS_EQUAL start)
    message(FATAL_ERROR "Neural Rendering request parser boundaries are missing")
endif()
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${source}" ${start} ${length} parser)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_rendering_request_under_test.h" "${parser}")
