if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
foreach(kind IN ITEMS page widget)
    if(kind STREQUAL "page")
        set(path "src/Menu/SettingsPage.cpp")
        set(marker "namespace MenuUI")
    else()
        set(path "src/Utils/Slider.cpp")
        set(marker "namespace Util::Widgets")
    endif()
    file(READ "${PROJECT_ROOT}/${path}" source)
    string(FIND "${source}" "${marker}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Settings UI namespace is missing")
    endif()
    string(SUBSTRING "${source}" ${start} -1 body)
    file(WRITE "${OUTPUT_DIRECTORY}/settings_${kind}_under_test.h" "${body}")
endforeach()
file(READ "${PROJECT_ROOT}/src/Utils/UI.h" source)
string(FIND "${source}" "\tnamespace Widgets" start)
string(FIND "${source}" "\n\tvoid UpdateImGuiInput" end)
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${source}" ${start} ${length} declarations)
file(WRITE "${OUTPUT_DIRECTORY}/settings_widget_declarations.h" "namespace Util { ${declarations} }")

file(READ "${PROJECT_ROOT}/src/Features/VolumetricLighting.cpp" source)
set(prefixes "")
foreach(method IN ITEMS DrawSettings DrawEssentialSettings)
    string(FIND "${source}" "void VolumetricLighting::${method}()" start)
    string(SUBSTRING "${source}" ${start} -1 rest)
    string(FIND "${rest}" "auto drawVRRestartHint" end)
    if(start LESS 0 OR end LESS 0)
        message(FATAL_ERROR "Volumetric lighting page preamble is missing")
    endif()
    string(SUBSTRING "${rest}" 0 ${end} prefix)
    string(APPEND prefixes "${prefix}}\n")
endforeach()
file(WRITE "${OUTPUT_DIRECTORY}/settings_lighting_pages_under_test.h" "${prefixes}")

include("${CMAKE_CURRENT_LIST_DIR}/extract_source_region.cmake")
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" source)
extract_between("${source}"
    "\tvoid DrawNeuralModelResolutionSettings("
    "\tvoid DrawNeuralRenderingSharedImageSettings("
    "settings_model_resolution_under_test.h")
