if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/NeuralRendering/D3D12Interop.cpp" source)
string(FIND "${source}" "struct ExecutionWaitScope" start)
string(FIND "${source}" "std::wstring WidenName" end)
if(start LESS 0 OR end LESS start)
    message(FATAL_ERROR "Execution wait test cannot extract the production scope")
endif()
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${source}" ${start} ${length} scope)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_execution_wait_scope.h" "namespace NeuralRendering {\n${scope}\n}\n")
