if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/VRRenderScaleDevBenchBridge.cpp" source)
string(FIND "${source}" "\tstruct RendererCommand\n" first)
string(FIND "${source}" "\tjson BuildQualificationReceipt(" last)
if(first LESS 0 OR last LESS first)
    message(FATAL_ERROR "Renderer dispatch extraction boundaries changed")
endif()
math(EXPR length "${last} - ${first}")
string(SUBSTRING "${source}" ${first} ${length} body)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_renderer_ownership_under_test.h" "${body}")

# Every NR transition entry must acquire ownership before reading or changing settings.
foreach(action IN ITEMS nr_configure nr_cycle_modes nr_reset foveation_configure foveation_cycle)
    string(FIND "${source}" "if (action == \"${action}\") {" start)
    if(start LESS 0)
        message(FATAL_ERROR "Missing ${action} handler")
    endif()
    string(SUBSTRING "${source}" ${start} -1 handler)
    string(REGEX MATCH "Run(OnMainThread|WithRendererOwnership)\\(" dispatcher "${handler}")
    if(NOT dispatcher STREQUAL "RunWithRendererOwnership(")
        message(FATAL_ERROR "${action} bypasses renderer ownership")
    endif()
endforeach()

# Only the supported NR tools may be registered.
file(READ "${PROJECT_ROOT}/src/Features/NeuralRenderingFeature.cpp" feature_source)
