if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" source)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.h" header)
string(FIND "${source}" "\tuint64_t BuildNeuralRenderingSettingsKey(" start)
string(FIND "${source}" "\tuint64_t BuildResourceCheckStableKey(" end)
math(EXPR length "${end} - ${start}")
if(start LESS 0 OR length LESS 1)
    message(FATAL_ERROR "NR settings key boundaries are missing")
endif()
string(SUBSTRING "${source}" ${start} ${length} function_body)
string(REGEX MATCHALL "a_settings\\.[A-Za-z0-9_]+" fields "${function_body}")
list(REMOVE_DUPLICATES fields)
set(settings "struct Upscaling { struct Settings {\n")
foreach(field IN LISTS fields)
    string(REPLACE "a_settings." "" field "${field}")
    string(REGEX MATCH "(bool|float|uint) ${field} *=" declaration "${header}")
    if(NOT declaration)
        message(FATAL_ERROR "NR field type missing: ${field}")
    endif()
    string(APPEND settings "${CMAKE_MATCH_1} ${field}{};\n")
endforeach()
string(APPEND settings "}; };\n")
string(FIND "${source}" "\tuint64_t HashResourceCheckValue(" hash_start)
string(FIND "${source}" "\tuint64_t BuildUpscalingResourceMutationSettingsKey(" hash_end)
math(EXPR hash_length "${hash_end} - ${hash_start}")
string(SUBSTRING "${source}" ${hash_start} ${hash_length} hash_helpers)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_settings_key_under_test.h"
    "${settings}\n${hash_helpers}\n${function_body}")
