if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
include("${CMAKE_CURRENT_LIST_DIR}/extract_source_region.cmake")
extract_between("${_source}" "\ttemplate <class Fn>\n\tstruct ScopeExit" "\tconstexpr float kPeripheryTAAOuterScaleMin" "vendor_texture_scope_exit.h")
extract_between("${_source}" "\tstd::uintptr_t GetCOMIdentityAddress(" "\tbool IsRenderScaleQualityMode(" "vendor_texture_identity.h")
extract_between("${_source}" "\tbool SameTexture2DDesc(" "\tbool IsVRDepthEncodeSourceValid(" "vendor_texture_resource.h")
extract_between("${_source}" "\tbool HasCompatibleCommonVendorViews(" "\tD3D11_TEXTURE2D_DESC BuildFlatRuntimeFsrDepthDesc(" "vendor_texture_validation.h")
