if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" source)
string(FIND "${source}" "bool Upscaling::PrepareReducedResolutionNeuralOutput(" start)
string(FIND "${source}" "bool Upscaling::ResolveCharacterCompositeInputs(" end)
if(start LESS 0 OR end LESS_EQUAL start)
    message(FATAL_ERROR "Reduced selection boundaries are missing")
endif()
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${source}" ${start} ${length} body)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_reduced_selection_under_test.h" "${body}")
