if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/NeuralRendering/Renderer.cpp" source)
string(FIND "${source}" "\tstd::optional<std::uint64_t> LogicalTextureBytes(" start)
string(FIND "${source}" "\n\tnamespace\n" end)
math(EXPR length "${end} - ${start}")
if(start LESS 0 OR length LESS 1)
    message(FATAL_ERROR "NR texture accounting boundaries are missing")
endif()
string(SUBSTRING "${source}" ${start} ${length} function_body)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/nr_model_resolution_accounting_under_test.h"
    "#pragma once\n#include <DirectXTex.h>\nnamespace NeuralRendering {\n${function_body}\n}\n")
