if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
function(extract_function name output)
    set(_return_type "void")
    if(ARGC GREATER 2)
        set(_return_type "${ARGV2}")
    endif()
    string(FIND "${_source}" "${_return_type} Upscaling::${name}(" _start)
    if(_start LESS 0)
        message(FATAL_ERROR "Cannot find ${name}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _tail)
    string(FIND "${_tail}" "\n}\n" _length)
    if(_length LESS 0)
        message(FATAL_ERROR "Cannot delimit ${name}")
    endif()
    math(EXPR _length "${_length} + 3")
    string(SUBSTRING "${_tail}" 0 ${_length} _function)
    set(${output} "${_function}" PARENT_SCOPE)
endfunction()

extract_function(PrepareMainFullResolutionNeuralFrame _prepare)
extract_function(GetNeuralTemporalFallbackReason _fallback "Upscaling::NeuralStereoFallbackReason")
extract_function(ApplyMainFinalLdrNeuralStereo _apply)
extract_function(PerformUpscaling _upscale)
extract_function(Main_PostProcessing::thunk _postprocess)
if(_apply MATCHES "PrepareMainFullResolutionNeuralFrame")
    message(FATAL_ERROR "Late final-LDR hook must only consume preparation")
endif()
if(NOT _upscale MATCHES "Upscale\\(\\);[\n\r\t ]+PrepareMainFullResolutionNeuralFrame\\(\\);[\n\r\t ]+UpscaleDepth\\(\\);")
    message(FATAL_ERROR "Vendor guide capture must precede depth upscaling")
endif()
if(NOT _postprocess MATCHES "else \\{[\n\r\t ]+upscaling.PrepareMainFullResolutionNeuralFrame\\(\\);[\n\r\t ]+if \\(globals::game::isVR\\)[\n\r\t ]+upscaling.UpscaleDepth\\(\\);")
    message(FATAL_ERROR "Native/TAA guide capture must precede postprocessing on all runtimes")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_full_resolution_preparation_under_test.h" "${_fallback}\n${_prepare}\n")
