if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" source)
function(extract start_marker end_marker output)
    string(FIND "${source}" "${start_marker}" start)
    if(start LESS 0)
        message(FATAL_ERROR "FOV geometry start missing: ${start_marker}")
    endif()
    string(SUBSTRING "${source}" ${start} -1 remaining)
    string(FIND "${remaining}" "${end_marker}" length)
    if(length LESS_EQUAL 0)
        message(FATAL_ERROR "FOV geometry end missing: ${end_marker}")
    endif()
    string(SUBSTRING "${remaining}" 0 ${length} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
extract("float2 Upscaling::GetDefaultFoveatedMaskCenterOffset(" "std::array<float2, 2> Upscaling::GetActiveResolvedFoveatedMaskCenterOffsets(" geometry)
extract("\tstruct FoveatedMaskProfileParams" "\tfloat FoveatedMaskDistanceUV(" parameters)
extract("\tfloat ClampFoveatedMaskOffsetAdjustment(" "\tuint ClampToggleUInt(" offset_clamp)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(
    WRITE "${OUTPUT_DIRECTORY}/foveated_mask_geometry_under_test.h"
    "${offset_clamp}\n${parameters}\n${geometry}"
)
