if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Hooks.cpp" _source)
string(FIND "${_source}" "struct IDXGISwapChain_Present" _present)
if(_present EQUAL -1)
    message(FATAL_ERROR "Cannot locate the production Present hook")
endif()
string(SUBSTRING "${_source}" ${_present} -1 _source)
string(FIND "${_source}" "state->Reset();" _start)
string(FIND "${_source}" "globals::features::screenshotFeature.OnBeforePresent" _end)
if(_start EQUAL -1 OR _end EQUAL -1 OR _end LESS_EQUAL _start)
    message(FATAL_ERROR "Cannot locate the production render-frame lifecycle")
endif()
math(EXPR _length "${_end} - ${_start}")
string(SUBSTRING "${_source}" ${_start} ${_length} _lifecycle)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/imgui_vr_helper_render_lifecycle_under_test.h" "${_lifecycle}")
