if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Globals.cpp" source)
string(FIND "${source}" "\tvoid CacheFramebuffer(" start)
string(FIND "${source}" "\tvoid InstallVRFrameBufferUploadHook()" end)
if(start EQUAL -1 OR end EQUAL -1 OR end LESS_EQUAL start)
    message(FATAL_ERROR "Camera upload boundaries are missing")
endif()
math(EXPR length "${end} - ${start}")
string(SUBSTRING "${source}" ${start} ${length} observer)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/nr_camera_upload_under_test.h" "${observer}")
