if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
include("${PROJECT_ROOT}/tests/extract_source_region.cmake")
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/NeuralRendering/D3D12Interop.cpp" source)
extract_between("${source}" "std::wstring WidenName" "D3D12Interop::~D3D12Interop" "helpers.h")
extract_between("${source}" "bool D3D12Interop::RecordFailureLocked" "bool D3D12Interop::Initialize" "resources.h")
extract_between("${source}" "bool D3D12Interop::BeginFeatureTiming" "bool D3D12Interop::EndD3D12" "queries.h")
file(WRITE "${OUTPUT_DIRECTORY}/neural_gpu_timing_under_test.h" "namespace NeuralRendering { namespace {\n")
file(READ "${OUTPUT_DIRECTORY}/helpers.h" section)
file(APPEND "${OUTPUT_DIRECTORY}/neural_gpu_timing_under_test.h" "${section}\n")
foreach(part IN ITEMS resources queries)
    file(READ "${OUTPUT_DIRECTORY}/${part}.h" section)
    file(APPEND "${OUTPUT_DIRECTORY}/neural_gpu_timing_under_test.h" "${section}\n")
endforeach()
file(APPEND "${OUTPUT_DIRECTORY}/neural_gpu_timing_under_test.h" "}\n")
