if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
string(FIND "${_source}" "struct VRFinalLdrPresentationHook" _start)
string(FIND "${_source}" "void Upscaling::PostPostLoad()" _end)
if(_start LESS 0 OR _end LESS _start)
    message(FATAL_ERROR "VR final scene boundary hook is missing")
endif()
math(EXPR _length "${_end} - ${_start}")
string(SUBSTRING "${_source}" ${_start} ${_length} _hook)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_presentation_hook_under_test.h" "${_hook}")
