if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/LegacyUtilityCompatibility.cpp" source)
string(FIND "${source}" "\nnamespace\n{" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Legacy utility adapter implementation was not found")
endif()
string(SUBSTRING "${source}" ${begin} -1 implementation)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/legacy_utility_compatibility_under_test.h" "${implementation}")
