file(READ "${PROJECT_ROOT}/src/Features/Upscaling/VRRenderScaleDevBenchBridge.cpp" source)
string(FIND "${source}" "\tjson BuildNeuralReplayResult(" first)
string(FIND "${source}" "\tvoid NeuralReplayToolHandler(" last)
if(first LESS 0 OR last LESS first)
    message(FATAL_ERROR "Native replay request boundary changed")
endif()
math(EXPR length "${last} - ${first}")
string(SUBSTRING "${source}" ${first} ${length} body)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_replay_request_under_test.h" "${body}")
