if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/NeuralRendering/Renderer.cpp" renderer)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/NeuralRendering/ColorPipeline.cpp" pipeline)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" upscaling)
function(extract source start_marker end_marker output)
    string(FIND "${${source}}" "${start_marker}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Colour route test missing ${start_marker}")
    endif()
    string(SUBSTRING "${${source}}" ${start} -1 tail)
    string(FIND "${tail}" "${end_marker}" end)
    if(end LESS 0)
        message(FATAL_ERROR "Colour route test missing ${end_marker}")
    endif()
    string(SUBSTRING "${tail}" 0 ${end} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(require_order source before after)
    string(FIND "${${source}}" "${before}" first)
    string(FIND "${${source}}" "${after}" second)
    if(first LESS 0 OR second LESS first)
        message(FATAL_ERROR "Colour route must order ${before} before ${after}")
    endif()
endfunction()
extract(renderer "\t\tstruct ColorTransactionKey" "\t\tD3D12Interop interop_" transaction)
extract(renderer "\t\tvoid CaptureColorConfiguration(" "\t\tvoid FinishCapture(" capture)
extract(pipeline "\t\tstruct Constants" "\t\tbool CreateTexture(" constants)
extract(pipeline "\t\twork.observation = std::move(observation);" "\t\tstd::uint64_t pixelBytes" work_latch)
extract(pipeline "\tbool Pipeline::Reconstruct(" "\tvoid Pipeline::Measure(" reconstruct)
extract(reconstruct "if (!context" "\t\tconst auto& config = work.configuration;" reconstruct_preflight)
require_order(reconstruct "requested.revision != work.configuration.revision" "context->UpdateSubresource(")

foreach(entry IN ITEMS Apply ApplyStereo ApplySequentialStereo)
    extract(renderer "\tbool Renderer::${entry}(" "\n\t}\n" entry_source)
    require_order(entry_source "state_->CaptureColorConfiguration(" "state_->${entry}Locked(")
endforeach()
extract(renderer "\tbool Renderer::State::ApplyBatchLocked(" "\n\tRenderer& Renderer::Instance()" batch)
require_order(batch "colorPipeline_.Prepare(" "colorPipeline_.Reconstruct(")
require_order(batch "colorPipeline_.Reconstruct(" "colorPipeline_.Commit(")
extract(renderer "\tbool Renderer::State::ApplySequentialStereoLocked(" "\tbool Renderer::State::ApplyBatchLocked(" sequential)
require_order(sequential "colorConfiguration_.Enabled()" "return ApplyBatchLocked(a_args, a_outcome)")
extract(upscaling "bool Upscaling::ApplyFinalLdrNeuralStereo(" "bool Upscaling::PrepareFullResolutionNeuralInputs(" final_route)
require_order(final_route "EvaluatePreparedNeuralStereo(" "DispatchFoveatedBlendPass(")
extract(upscaling "\tNeuralStereoEvaluationSummary EvaluatePreparedNeuralStereo(" "bool Upscaling::ApplyFinalLdrNeuralStereo(" evaluation)
require_order(evaluation "NeuralRendering::Renderer::Instance().ApplyStereo(" "PrepareReducedResolutionNeuralOutput(")
extract(renderer "\t\tstruct HistoryKey" "\t\tstruct Slot" history)
if(NOT history MATCHES "colorInputEpoch" OR history MATCHES "lightingPreservation|[Cc]olorRevision")
    message(FATAL_ERROR "Reconstruction-only controls must not enter inference history identity")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_color_route_latch_state.h" "${transaction}\n${capture}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_color_route_latch_pipeline.h"
    "namespace NeuralRendering::Color {\n${constants}\n"
    "void LatchWork(Work& work, const Configuration& config, Observation observation) { std::uint64_t measurementOrder_ = 0;\n${work_latch}\n}\n"
    "// Only handle presence is modeled; the exact production preflight runs before any GPU work.\n"
    "struct ReconstructionPreflight {\n"
    "bool context = true, neural = true, neuralSRV = true, preparedSRV = true, reconstruct_ = true, constants_ = true;\n"
    "struct { struct { bool uav = true; } result; bool prepared = true; Configuration configuration; } work;\n"
    "bool Admit(const Configuration& requested) {\n${reconstruct_preflight}\nreturn true;\n}\n};\n}\n")
