include("${PROJECT_ROOT}/tests/extract_source_region.cmake")
get_filename_component(OUTPUT_DIRECTORY "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(READ "${PROJECT_ROOT}/src/Features/VolumetricLighting.cpp" _source)
file(READ "${PROJECT_ROOT}/src/Features/VolumetricLighting.h" _header)
extract_between("${_header}" "\tstruct TextureSize" "\nprivate:" vl_runtime_settings.h)
extract_between("${_source}" "\tconstexpr int32_t kTextureWidthMin" "\n\tbool IsImageSpaceReplacementEnabled()" vl_runtime_limits.h)
extract_between("${_source}" "int32_t VolumetricLighting::ClampQualityIndex(" "bool VolumetricLighting::TryGetActiveGodrayProfile(" vl_runtime_settings_methods.h)
extract_between("${_source}" "bool VolumetricLighting::TryGetActiveGodrayProfile(" "VolumetricLighting::GodrayProfile VolumetricLighting::GetRuntimeGodrayProfile()" vl_runtime_profile.h)
extract_between("${_source}" "bool VolumetricLighting::IsPerformanceCostMeasurementEnabled()" "void VolumetricLighting::SetPerformanceCostMeasurementEnabled(" vl_runtime_measurement.h)
extract_between("${_source}" "void VolumetricLighting::SetExteriorEnabled(" "void VolumetricLighting::PostPostLoad()" vl_runtime_api.h)
extract_between("${_source}" "void VolumetricLighting::EarlyPrepass()" "void VolumetricLighting::ClearVolumetricLightingTargets()" vl_runtime_apply.h)
set(_runtime "")
foreach(_part limits settings_methods profile measurement api apply)
    file(READ "${OUTPUT_DIRECTORY}/vl_runtime_${_part}.h" _text)
    string(APPEND _runtime "${_text}\n")
endforeach()
file(WRITE "${OUTPUT_FILE}" "${_runtime}")

file(READ "${PROJECT_ROOT}/src/Features/InteriorSun.cpp" _sun)
file(READ "${PROJECT_ROOT}/src/Features/InverseSquareLighting.cpp" _inverse)
extract_between("${_sun}" "void InteriorSun::EarlyPrepass()" "inline bool InteriorSun::IsInteriorWithSun(" sun_apply.h)
extract_between("${_sun}" "void InteriorSun::SetRuntimeEnabled(" "void InteriorSun::PopulateReplacementJobArrays(" sun_request.h)
extract_between("${_inverse}" "void InverseSquareLighting::SetRuntimeEnabled(" "void InverseSquareLighting::ApplyRuntimeStateToActiveLights()" inverse_apply.h)
foreach(_part sun_apply sun_request inverse_apply)
    file(READ "${OUTPUT_DIRECTORY}/${_part}.h" _text)
    file(APPEND "${OUTPUT_FILE}" "${_text}\n")
endforeach()
