if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

function(extract path start_marker end_marker output)
    file(READ "${PROJECT_ROOT}/${path}" source)
    string(FIND "${source}" "${start_marker}" start)
    string(FIND "${source}" "${end_marker}" end)
    if(start LESS 0 OR end LESS_EQUAL start)
        message(FATAL_ERROR "NR resource-key extraction boundary missing: ${start_marker}")
    endif()
    math(EXPR length "${end} - ${start}")
    string(SUBSTRING "${source}" ${start} ${length} result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

set(source "src/Features/Upscaling.cpp")
set(header "src/Features/Upscaling.h")
extract("${header}" "\tenum class VRRenderScaleBackendKind" "\tstruct VRRenderScaleResourceCompatibility" types)
extract("${header}" "\tstruct VRRenderScaleProfileSnapshot\n" "\t/** @brief Coherent read model" profile)
extract("${source}" "\tstruct FoveatedMaskProfileParams" "\tfloat FoveatedMaskDistanceUV(" mask_profile)
extract("${source}" "\tbool SupportsFoveatedVendorDispatch(" "\tbool ShouldUseReducedResolutionForUpscaling(" configuration)
extract("${source}" "bool Upscaling::IsNeuralRenderingRenderScaleRequired() const noexcept" "NeuralRendering::RenderingMode Upscaling::GetNeuralRenderingMode()" neural_gate)
extract("${source}" "bool Upscaling::IsFoveatedVendorDispatchEnabled(" "bool Upscaling::IsFSRRuntimePathActive(" dispatch_gate)
extract("${source}" "bool Upscaling::IsPeripheryTAAEnabled(" "bool Upscaling::IsPeripheryTAAPathActive(" taa_gate)
extract("${source}" "Upscaling::VRRenderScaleResourceKey Upscaling::BuildVRRenderScaleResourceKey(" "Upscaling::VRRenderScaleResourceCompatibility Upscaling::CompareVRRenderScaleResourceKeys(" resource_key)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_resource_key_types.h" "${types}\n${profile}")
file(WRITE "${OUTPUT_DIRECTORY}/neural_resource_key_under_test.h"
    "${mask_profile}\n${configuration}\n${neural_gate}\n${dispatch_gate}\n${taa_gate}\n${resource_key}")
