if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_FILE are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/Skylighting.cpp" _source)
string(FIND "${_source}" "void NormalizeSettingsForRuntime(" _start)
if(_start EQUAL -1)
    message(FATAL_ERROR "Skylighting settings test cannot find the runtime normalizer")
endif()
string(SUBSTRING "${_source}" ${_start} -1 _remaining)
string(FIND "${_remaining}" "\n\tbool IsTexture2DArraySRV(" _end)
if(_end EQUAL -1)
    message(FATAL_ERROR "Skylighting settings test cannot find the normalizer boundary")
endif()
string(SUBSTRING "${_remaining}" 0 ${_end} _normalizer)
get_filename_component(_output_directory "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_directory}")
file(WRITE "${OUTPUT_FILE}" "${_normalizer}\n")
