cmake_minimum_required(VERSION 4.2)
if(NOT PROJECT_ROOT OR NOT TEST_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT and TEST_ROOT are required")
endif()
set(NR_RELEASE_ROOT "${TEST_ROOT}/payload")
set(NR_RELEASE_FILES "")
set(NR_RELEASE_HASHES "")
set(_runtime_root "${NR_RELEASE_ROOT}/Shaders/Upscaling/Streamline")
file(MAKE_DIRECTORY "${_runtime_root}")
foreach(_name IN ITEMS nvngx_dlss.dll sl.common.dll license.txt)
    file(WRITE "${_runtime_root}/${_name}" "official fixture ${_name}")
    file(SHA256 "${_runtime_root}/${_name}" _hash)
    list(APPEND NR_RELEASE_FILES "${_name}")
    list(APPEND NR_RELEASE_HASHES "${_hash}")
endforeach()
file(WRITE "${TEST_ROOT}/verify.cmake"
    "set(NR_RELEASE_ROOT [==[${NR_RELEASE_ROOT}]==])\nset(NR_RELEASE_FILES [==[${NR_RELEASE_FILES}]==])\nset(NR_RELEASE_HASHES [==[${NR_RELEASE_HASHES}]==])\ninclude([==[${PROJECT_ROOT}/cmake/VerifyNrReleasePayload.cmake]==])\n")
function(check expected pattern)
    set(_script "${TEST_ROOT}/verify.cmake")
    if(ARGC GREATER 2)
        set(_script "${ARGV2}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_script}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(expected STREQUAL "pass")
        if(NOT _result EQUAL 0)
            message(FATAL_ERROR "Valid release rejected: ${_stdout}${_stderr}")
        endif()
    elseif(_result EQUAL 0 OR NOT "${_stdout}${_stderr}" MATCHES "${pattern}")
        message(FATAL_ERROR "Invalid release was not rejected correctly: ${_stdout}${_stderr}")
    endif()
endfunction()
check(pass "")
file(WRITE "${NR_RELEASE_ROOT}/INTERNAL-NO-REDISTRIBUTION.txt" "internal fixture")
check(fail "Internal provider notices")
file(REMOVE "${NR_RELEASE_ROOT}/INTERNAL-NO-REDISTRIBUTION.txt")
foreach(_name IN ITEMS nvngx_dlssnr.dll sl.dlss_nr.dll extra.license.txt)
    file(WRITE "${_runtime_root}/${_name}" "unexpected fixture")
    check(fail "unexpected files|never packaged")
    file(REMOVE "${_runtime_root}/${_name}")
endforeach()
file(MAKE_DIRECTORY "${NR_RELEASE_ROOT}/other")
file(WRITE "${NR_RELEASE_ROOT}/other/NVNGX_DLSSNR_backup.DLL" "unexpected fixture")
check(fail "never packaged")
file(REMOVE "${NR_RELEASE_ROOT}/other/NVNGX_DLSSNR_backup.DLL")
file(WRITE "${_runtime_root}/sl.common.dll" "modified fixture")
check(fail "differs from the pinned SDK")
file(REMOVE "${_runtime_root}/sl.common.dll")
check(fail "missing official SDK file")
set(_shader_root "${NR_RELEASE_ROOT}/Shaders/Upscaling/NeuralRendering")
file(MAKE_DIRECTORY "${_shader_root}")
file(WRITE "${_shader_root}/ColorPrepareCS.hlsl" "valid shader fixture")
# Restore the official fixture before inspecting the unrelated shader tree.
file(WRITE "${_runtime_root}/sl.common.dll" "official fixture sl.common.dll")
check(pass "")
foreach(_unexpected IN ITEMS descriptor.json native.cubin)
    file(WRITE "${_shader_root}/${_unexpected}" "unexpected fixture")
    check(fail "Unexpected NR shader payload")
    if(NOT EXISTS "${_shader_root}/${_unexpected}")
        message(FATAL_ERROR "NR payload guard altered the rejected file")
    endif()
    file(REMOVE "${_shader_root}/${_unexpected}")
endforeach()
file(MAKE_DIRECTORY "${_shader_root}/Experimental")
check(fail "Unexpected NR shader payload")
if(NOT IS_DIRECTORY "${_shader_root}/Experimental")
    message(FATAL_ERROR "NR payload guard removed the rejected directory")
endif()
file(REMOVE_RECURSE "${_shader_root}/Experimental")
message(STATUS "NR release payload rejects extra files, NR DLLs, modified SDK files and missing files")
