cmake_minimum_required(VERSION 4.2)
if(NOT PROJECT_ROOT OR NOT TEST_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT and TEST_ROOT are required")
endif()
set(NR_RELEASE_ROOT "${TEST_ROOT}/payload")
set(NR_RELEASE_FILES "")
set(NR_RELEASE_HASHES "")
set(_runtime_root "${NR_RELEASE_ROOT}/Shaders/Upscaling/Streamline")
file(MAKE_DIRECTORY "${_runtime_root}")
foreach(_name IN ITEMS nvngx_dlss.dll sl.common.dll license.txt)
    file(WRITE "${_runtime_root}/${_name}" "official fixture ${_name}")
    file(SHA256 "${_runtime_root}/${_name}" _hash)
    list(APPEND NR_RELEASE_FILES "${_name}")
    list(APPEND NR_RELEASE_HASHES "${_hash}")
endforeach()
file(WRITE "${TEST_ROOT}/verify.cmake"
    "set(NR_RELEASE_ROOT [==[${NR_RELEASE_ROOT}]==])\nset(NR_RELEASE_FILES [==[${NR_RELEASE_FILES}]==])\nset(NR_RELEASE_HASHES [==[${NR_RELEASE_HASHES}]==])\ninclude([==[${PROJECT_ROOT}/cmake/VerifyNrReleasePayload.cmake]==])\n")
function(check expected pattern)
    set(_script "${TEST_ROOT}/verify.cmake")
    if(ARGC GREATER 2)
        set(_script "${ARGV2}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_script}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(expected STREQUAL "pass")
        if(NOT _result EQUAL 0)
            message(FATAL_ERROR "Valid release rejected: ${_stdout}${_stderr}")
        endif()
    elseif(_result EQUAL 0 OR NOT "${_stdout}${_stderr}" MATCHES "${pattern}")
        message(FATAL_ERROR "Invalid release was not rejected correctly: ${_stdout}${_stderr}")
    endif()
endfunction()
check(pass "")
foreach(_name IN ITEMS nvngx_dlssnr.dll sl.dlss_nr.dll extra.license.txt)
    file(WRITE "${_runtime_root}/${_name}" "private fixture")
    check(fail "unexpected files")
    file(REMOVE "${_runtime_root}/${_name}")
endforeach()
file(MAKE_DIRECTORY "${NR_RELEASE_ROOT}/other")
file(WRITE "${NR_RELEASE_ROOT}/other/NVNGX_DLSSNR_backup.DLL" "private fixture")
check(fail "never packaged")
file(REMOVE "${NR_RELEASE_ROOT}/other/NVNGX_DLSSNR_backup.DLL")
file(WRITE "${_runtime_root}/sl.common.dll" "modified fixture")
check(fail "differs from the pinned SDK")
file(REMOVE "${_runtime_root}/sl.common.dll")
check(fail "missing official SDK file")
foreach(_private_input IN ITEMS CSX_LOCAL_DLSSNR_RUNTIME_FILE CSX_NR_KERNEL_PAYLOAD_DIR)
    set(_script "${TEST_ROOT}/${_private_input}.cmake")
    file(WRITE "${_script}"
        "cmake_minimum_required(VERSION 4.2)\nset(CSX_NR_RELEASE_PACKAGE ON)\nset(${_private_input} private-fixture CACHE FILEPATH \"\" FORCE)\ninclude([==[${PROJECT_ROOT}/cmake/NeuralRenderingRuntime.cmake]==])\n")
    check(fail "cannot include a local NR runtime" "${_script}")
endforeach()
set(_script "${TEST_ROOT}/skip-downloads.cmake")
file(WRITE "${_script}"
    "cmake_minimum_required(VERSION 4.2)\nset(CSX_NR_RELEASE_PACKAGE ON)\nset(SKIP_RUNTIME_DOWNLOADS ON)\nset(CMAKE_CURRENT_BINARY_DIR [==[${TEST_ROOT}/skip-build]==])\ninclude([==[${PROJECT_ROOT}/cmake/Streamline-Runtime.cmake]==])\n")
check(fail "SKIP_RUNTIME_DOWNLOADS must be OFF" "${_script}")
message(STATUS "NR release payload rejects extra files, NR DLLs, modified SDK files and missing files")
