function(csx_validate_neural_color source_root)
    set(feature_root "${source_root}/features/Neural Rendering")
    set(manifest "${feature_root}/Shaders/Features/NeuralRendering.ini")
    set(registry "${source_root}/include/FeatureVersions.h")
    foreach(required IN ITEMS "${manifest}" "${feature_root}/CORE" "${registry}")
        if(NOT EXISTS "${required}" OR IS_DIRECTORY "${required}")
            message(FATAL_ERROR "Neural Rendering registration requires ${required}")
        endif()
    endforeach()

    file(READ "${manifest}" manifest_text)
    string(REGEX MATCH "[Vv]ersion[ \t]*=[ \t]*([0-9]+)-([0-9]+)-([0-9]+)" version_match "${manifest_text}")
    if(NOT version_match)
        message(FATAL_ERROR "NeuralRendering.ini must declare a valid feature version")
    endif()
    set(manifest_version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")

    # The checked-in include overrides the generated registry during compilation.
    file(READ "${registry}" registry_text)
    string(REGEX MATCH "\\{[ \t\r\n]*\"NeuralRendering\"sv,[ \t\r\n]*\\{([0-9]+),[ \t]*([0-9]+),[ \t]*([0-9]+)\\}" registry_match "${registry_text}")
    if(NOT registry_match)
        message(FATAL_ERROR "Neural Rendering is missing from include/FeatureVersions.h")
    endif()
    set(registry_version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
    if(NOT registry_version VERSION_EQUAL manifest_version)
        message(FATAL_ERROR "Neural Rendering registry version ${registry_version} differs from manifest ${manifest_version}")
    endif()
    string(REGEX MATCH "FEATURE_CORE_NAMES[^;]*;" core_names "${registry_text}")
    if(NOT core_names MATCHES "\"NeuralRendering\"sv")
        message(FATAL_ERROR "Neural Rendering is missing from FEATURE_CORE_NAMES")
    endif()

    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${manifest}" "${feature_root}/CORE" "${registry}")
    endif()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT DEFINED CSX_NEURAL_COLOR_ROOT)
        message(FATAL_ERROR "CSX_NEURAL_COLOR_ROOT must identify the source checkout")
    endif()
    csx_validate_neural_color("${CSX_NEURAL_COLOR_ROOT}")
endif()
