foreach(_required IN ITEMS NR_RELEASE_ROOT NR_RELEASE_FILES NR_RELEASE_HASHES)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "${_required} is required for NR release validation")
    endif()
endforeach()
list(LENGTH NR_RELEASE_FILES _file_count)
list(LENGTH NR_RELEASE_HASHES _hash_count)
if(NOT _file_count EQUAL _hash_count)
    message(FATAL_ERROR "NR release file and hash inventories differ")
endif()

set(NR_PACKAGE_ROOT "${NR_RELEASE_ROOT}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyNeuralRenderingPayload.cmake")

set(_runtime_root "${NR_RELEASE_ROOT}/Shaders/Upscaling/Streamline")
set(_expected_names "")
foreach(_source _expected_hash IN ZIP_LISTS NR_RELEASE_FILES NR_RELEASE_HASHES)
    get_filename_component(_name "${_source}" NAME)
    list(APPEND _expected_names "${_name}")
    set(_installed "${_runtime_root}/${_name}")
    if(NOT EXISTS "${_installed}" OR IS_DIRECTORY "${_installed}")
        message(FATAL_ERROR "NR release is missing official SDK file: ${_name}")
    endif()
    file(SHA256 "${_installed}" _actual_hash)
    if(NOT _actual_hash STREQUAL _expected_hash)
        message(FATAL_ERROR "NR release SDK file differs from the pinned SDK: ${_name}")
    endif()
endforeach()
file(GLOB_RECURSE _actual_names LIST_DIRECTORIES TRUE RELATIVE "${_runtime_root}" "${_runtime_root}/*")
list(SORT _actual_names)
list(SORT _expected_names)
if(NOT _actual_names STREQUAL _expected_names)
    message(FATAL_ERROR "NR release Streamline folder contains unexpected files: ${_actual_names}")
endif()

message(STATUS "NR release contains only pinned Streamline SDK files and no NR DLLs")
