name: Package-nr

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    package:
        uses: ./.github/workflows/_shared-build.yaml
        with:
            ref: ${{ github.ref }}
            repository: ${{ github.repository }}
            package-nr: true
            artifact-name: Package-nr
            run-shader-validation: false
            run-shader-tests: false
